app/assets/javascripts/multi_search.js

#21 
The size of an arc is calculated by taking the sum of the sizes of its "children". If a node doesn't have any children, its size is proportional to the number of peptides unique to that node.
Let's look at a toy example:
```
Parent (15)
|--Child 1 (7)
| |--Subchild 1 (1)
| |--Subchild 2 (3)
|--Child 2 (3)
```
- Both subchildren have no children, so their sizes are proportional to the number of peptides they have (1 and 3). 
- Child 1 has two children, so its size is the sum of the sizes of the children (3+1 = 4)
- Child 2 has no children, so its size is 3
- Parent has two children, so its size is the sum of the sizes of child 1 and 2 (4+3 = 7)
As you can see, the size of the parent (7) doesn't match with the number of peptides of that node (15). This is probably what you also …

add empty slices to sunburst

---

Gemfile
Gemfile.lock
config/environments/development.rb
config/environments/production.rb

Closes #283 
Actionmailer configuration needs to be done. 
I suggest using `sendmail` which is easy to setup.
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/312) by ghost on Mon May 12 2014 at 09:20._
_Merged by @bmesuere on Tue May 13 2014 at 13:46._

add exception notification gem

---

app/assets/javascripts/multi_search.js
app/assets/stylesheets/application.css.less
app/views/sequences/multi_search.html.erb

Closes #367 
There seem to be some issues with adding 2 jit visualisations to the same page. The rendering of the labels is bugged:
- the treemap labels are not shown
- the treeview labels are shown on the treemap
Switching the treeview to Native labels instead of HTML labels fixes this issue, but there's no event handling for Native labels which means no zooming.
One solution might be to implement a custom label type based on the HTML labels: https://github.com/philogb/jit/blob/master/Jit/jit.js#L7721
There's also an issue with the canvas rendering on hidpi displays: http://www.html5rocks.com/en/tutorials/canvas/hidpi/
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/381) by @bmesuere on Sun Jun 15 2014 at 21:15._
_Merged by @bmesuere on Sun Jul 06 2014 at 12:04._

add treeview to multi search

---

app/controllers/pride_controller.rb
config/application.rb
test/controllers/pride_controller_test.rb

The PRIDE BioMart will be retired by the end of this year. This PR replaces the BioMart API call with a similar PRIDE API call.
This can't be merged yet, because the API call we're using isn't in production yet. This should be the case by the end of november and can be checked at http://www.ebi.ac.uk/pride/ws/archive/.
There currently isn't a way to load all peptides at once, so we just use a very big number. The PRIDE people warned us about this:
> To get all results at once (although we would discourage this use), you
> have to use a high enough value or the value of the result count, which
> you can get with /peptide/count/assay.
> Although it might be possible to download all peptides at once, this is
> a much heavier operation than with the pages result. We did not have
> very good …

hotfix: replace biomart with PRIDE API

---

backend/proteomes.sh

I was testing #555 and I had to wait too long for this last step. I used 10 processes for now, speed can still be increased in the future if required.
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/556) by @ninewise on Thu Jan 28 2016 at 10:51._
_Merged by @ninewise on Mon Feb 01 2016 at 14:17._

run curls to uniprot in parallel

---

backend/config
backend/makefile
backend/pom.xml
backend/src/main/java/org/unipept/storage/CSV.java
backend/src/main/java/org/unipept/storage/TableWriter.java
backend/src/main/java/org/unipept/tools/LineagesSequencesTaxons2LCAs.java
backend/src/main/java/org/unipept/tools/NamesNodes2Taxons.java
backend/src/main/java/org/unipept/tools/NamesNodes2TaxonsLineages.java
backend/src/main/java/org/unipept/tools/TaxonsUniprots2Tables.java
backend/src/main/java/org/unipept/xml/UniprotEntry.java
backend/src/main/java/org/unipept/xml/UniprotHandler.java
backend/src/test/java/org/unipept/xml/UniprotHandlerTest.java

This PR contains several optimizations of the UniProt processing pipeline:
- stop using BerkeleyDB and assign sequence id's during post processing (also reduces memory requirements)
- custom protein digest
- use the unix gzip tools instead of gzip readers and writers in java
- smaller java tweaks
- using `LC_ALL=C` for the sort command increases performance by an order of magnitude
- use more memory and threads for the sort command
| &nbsp; | parse xml | join peptide uniprot | number sequences | sequence id | LCA calculation | join sequences | peptides id | **total** |
| :-- | --: | --: | --: | --: | --: | --: | --: | --: |
| initial code | 9h06m | 1h56m | - | - | 2 \* 50m | - | - | **12h42m** |
| without BDB | 5h30m | 2 \* 1h38 | 22m | 2 \* 19m | 2 \* 50m | 21m | 2h46 | **14h33m** |
| …

WIP: Optimize the UniProt parser

---

app/assets/javascripts/peptidome/pancoreGraph.js
app/assets/javascripts/workers/pancore_worker.js
app/controllers/peptidome_controller.rb
config/application.rb
config/routes.rb
test/controllers/peptidome_controller_test.rb

To accommodate a reviewer request, adds an option to download protein information from the unique peptide finder page:
The resulting data is saved as a csv file:
```
sequence,lca_taxon_id,uniprot_id,protein_name
AAAAYVR,1358,Q9CDY4,50S ribosomal protein L17
AAAAYVR,1358,Q02W52,50S ribosomal protein L17
AAAAYVR,1358,A2RNM6,50S ribosomal protein L17
AAADELGVPLYNYLGGFNAK,1358,Q9CHS7,Enolase 1
AAADELGVPLYNYLGGFNAK,1358,A2RIX1,Enolase
AAADELGVPLYNYLGGFNAK,1358,Q030Y9,Enolase 2
...
```
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/576) by @bmesuere on Mon Jun 06 2016 at 20:23._
_Merged by @bmesuere on Wed Jun 08 2016 at 18:41._

add option to download proteins to the unique peptide finder

---

backend/type_strains.sh.in

Using the wrong variable name resulted in only the first batch of type strains to be fetched.
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/578) by @ninewise on Fri Jun 10 2016 at 11:39._
_Merged by @ninewise on Fri Jun 10 2016 at 13:04._

quickfix: wrong batch size variable

---

.eslintrc
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/multisearch/multisearch.js
app/assets/javascripts/multisearch/searchtree.js
app/assets/javascripts/sequence_show.js
app/assets/javascripts/utils.js
app/assets/stylesheets/utilities.css.less
app/views/sequences/multi_search.html.erb
package.json
yarn.lock

Replace the flash based zero clipboard by a javascript solution.
closes #529 
fixes #559 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/615) by @bmesuere on Thu Aug 17 2017 at 10:52._
_Merged by @bmesuere on Thu Aug 17 2017 at 14:45._

migrate to clipboard.js

---

app/controllers/api/clidocs_controller.rb
app/views/api/clidocs/_getting_started.html.erb
app/views/api/clidocs/index.html.erb
app/views/api/clidocs/pept2prot.html.erb
app/views/api/shared/_sidebar.html.erb
config/application.rb

- bumps the minimal ruby version to 2.0
- bumps the recommended ruby version to 2.4
- bumps the gem version to 1.3.0
- add `--meganize` to the `unipept pept2prot` page
Closes #592
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/617) by @bmesuere on Thu Aug 17 2017 at 14:25._
_Merged by @bmesuere on Thu Aug 17 2017 at 16:22._

Update the command line docs

---

backend/createGoTerms.sh.in

I modified the script that gets GO terms so it duplicates entries that have multiple go-term numbers
---
In the obo file describing the GO terms, some entries had alternate IDs. These IDs were referenced in the `go_cross_refereces` which caused problems when agregating by namespace.
```
[Term]
id: GO:1990948
name: ubiquitin ligase inhibitor activity
namespace: molecular_function
alt_id: GO:0061637
alt_id: GO:0090645
...
```
With this edit the above `[Term]` is tranlated into 3 rows with identical go-term, name and namespace (but unique id)
This modification adds 2078 records to `go_terms`
---
In my opinion it would be better to either fix the referenced directly in the `go_cross_references` or to add an extra property to `go_term` that points to the original name. This would allow better …

Duplicate go_terms enteries that have alternative id's

---

backend/src/main/java/org/unipept/storage/CSV.java
backend/src/main/java/org/unipept/storage/TableWriter.java

Change the `IndexedWriter` to use a long as index rather than an int.+
In the database, the indexes are stored as `int(10)`, which is enough for now.
```bash
$ zcat tables/peptides.tsv.gz | wc -l
2353109178
```
An alternative to this solution is to use [`toUnsignedString(int i, int radix)`](https://docs.oracle.com/javase/8/docs/api/java/lang/Integer.html#toUnsignedString-int-int-)
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/633) by @beardhatcode on Fri Apr 06 2018 at 13:24._
_Merged by @bmesuere on Mon May 07 2018 at 16:59._

fix integer overflow for peptides

---

app/views/layouts/application.html.erb

This makes shure only the 
```
Refferer: https://unipept.ugent.be
```
is sent instead of the full url (http://localhost:5000/sequences/AALER/equateIL)
```
Refferer: https://unipept.ugent.be/sequences/AALER/equateIL
```
The additional benefit is that it does not break other sites if the Refferer is too long, which was the case for with QuickGO
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/640) by @beardhatcode on Thu Jun 14 2018 at 14:14._
_Merged by @bmesuere on Thu Jun 14 2018 at 14:44._

Only send Unipept as referer

---

backend/latest-config-hpc-phanpy
backend/make-on-hpc.sh

The HPC has reinstalled Slurm and phanpy lost some memory in the
processes. The queues have also been renamed. There is no longer a
"long" queue.
Also: The paths have changed. there are symlinks at the moment but it is better to update them now.
See #665
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/668) by @beardhatcode on Wed Mar 27 2019 at 11:36._
_Merged by @ninewise on Thu Mar 28 2019 at 13:22._

Update the config to run on the HPC

---

app/views/api/apidocs/pept2funct.html.erb
app/views/api/apidocs/pept2go.html.erb
app/views/api/apidocs/peptinfo.html.erb

We did change the API-parameter `split` to `domains` some time ago for the API-endpoints that return GO-terms. This change was however not reflected in the API-docs, which is now fixed in this pull request.

Renamed all occurrences of split in the documentation to domains

---

app/views/datasets/index.html.erb
app/views/mpa/analyze.html.erb
app/views/peptidome/analyze.html.erb
app/views/sequences/show.html.erb

D3 was included once through a script-tag and once through the d3_pack in some applications. This PR fixes the double inclusion.

Get rid of double D3-inclusion for some applications

---

vendor/assets/javascripts/vendor.js
yarn.lock

This PR fixes some problems that occur with the typeahead library and the peptidome analysis application.

Fix "typeahead is undefined" error

---

package.json
yarn.lock

By updating the Unipept Web Components to version 0.1.10 a lot of issues are fixed:
* fixes #916 
* fixes #914 
* fixes #913
* fixes #912 
* fixes #893

Bump web components to newest version

---

package.json
yarn.lock

This bumps the unipept-web-components to version 0.1.13 which adds the ability to export the treemap to an SVG.

Bump unipept-web-components to 0.1.13

---

.rubocop.yml
app/controllers/api/api_controller.rb

Some proteins are annotated with an InterPro-code that no longer exists and which is not present in the `interpro_entries`-table. This entry is then `nil` in `api_controller` and causes the application to crash.
An extra check is added to make sure that entries are valid before we are trying to use them.

Fixed crash due to some interpro entries being nil

---

package.json
yarn.lock

This version expands the export functionality with 4 new columns that include the human-readable names of the exported functional annotations.

Bump Unipept Web Components to 0.1.15

---

package.json

This release adds a third "export as TSV" option to the MPA results export section.

Bump UWC to 0.1.16

---

app/assets/javascripts/mpa/components/App.vue
app/assets/javascripts/mpa/components/dataset/LoadDatasetsCard.vue

This PR fixes a bug where the error "cannot read property join of undefined" occurs if the user tries to process a sample from local storage.

Fix "cannot read property join of undefined"

---

.github/workflows/uptime.yml
app/controllers/api/api_controller.rb
test/uptime/check_uptime_api.sh

This PR adds a new GitHub action that is automatically run every hour and checks the uptime of the API-server. It fails if a request does not return the expected results or if a requests takes longer than 10 seconds to execute.
A new flag for the `taxa2tree` command has been added (`remove`), which will automatically remove a newly created gist.

API monitoring action

---

app/controllers/api/api_controller.rb
config/deploy/dev.rb

This PR splits a very large and slow query in the `pept2taxa` API-endpoint into multiple small queries to speed up the processing of these queries.

speedup pept2taxa

---

.github/workflows/uptime.yml
test/uptime/check_api_response.sh
test/uptime/check_uptime_performance.sh

This PR splits the GitHub workflow to check the API-server's up status over 2 jobs: one job that checks the response from the server and one job that checks the performance of the server. This way, e-mail notifications of a failure are more clear and don't require manually checking the job output for which part of the check failed.

Split API checks over multiple file

---

config/environments/production.rb

By default, the log level is info. This PR changes that to error for the API branch/deploy.

Reduce logging

---

app/controllers/private_api_controller.rb
app/views/private_api/error.json.jbuilder

If no valid peptide sequence is provided to the `private_api/proteins` endpoint, an exception is generated. This pull request correctly catches this exception and instead generates a proper error message. 
This PR should make sure that we no longer receive error messages from the production server when someone (e.g. a bot) performs a request to `/private_api/proteins` with invalid input data.

Fix undefined method upcase for private_api/proteins

---

app/assets/javascripts/mpa/components/dataset/SwitchDatasetsCard.vue
package.json
yarn.lock

The data tables that are used to select items in a heatmap only count the peptides that are situated at a specific taxon rank, without also counting in all peptides that are associated with descending ranks. This PR fixes this issue.

Also count descendants in peptide count for taxa

---

Gemfile
Gemfile.lock
babel.config.js
bin/webpack
bin/webpack-dev-server
config/webpack/development.js
config/webpack/environment.js
config/webpack/loaders/typescript.js
package.json
tsconfig.json
yarn.lock

This PR updates Webpacker to version 5.2. Due to recent changes in the TypeScript compiler, an error "TS2729: property used before assignment" can be expected. This error originates from the current version of the unipept web components package, and will be fixed in a future version of this package.
Maybe we should wait to merge this PR until a new version of the Unipept web components package is released, which fixes this issue.

Update Webpacker to 5.2

---

config/application.rb

This PR increases the `key_space_limit` in order to allow large requests to our API to succeed.

Increase key space limit for larger requests

---

Gemfile.lock
app/controllers/api/api_controller.rb
app/helpers/api_helper.rb
app/models/lineage.rb
config/routes.rb
config/webpacker.yml
db/schema.rb
test/controllers/private_api_controller_test.rb
test/fixtures/lineages.yml
test/models/lineage_test.rb

This PR adds a new v2 of the Unipept API that differs in the ranks that are returned when requesting lineage information for a peptide.
Example for `api/v1/pept2taxa.json?input[]=MHEMSIAEGIVQLLEEQAAAQR&extra=true`:
```
[
{
"peptide": "MHEMSIAEGIVQLLEEQAAAQR",
"taxon_id": 355,
"taxon_name": "Azotobacter chroococcum (strain mcd 1)",
"taxon_rank": "strain",
"superkingdom_id": 2,
"kingdom_id": null,
"subkingdom_id": null,
"superphylum_id": null,
"phylum_id": 1224,
"subphylum_id": null,
"superclass_id": null,
"class_id": 1236,
"subclass_id": null,
"infraclass_id": null,
"superorder_id": null,
"order_id": 72274,
"suborder_id": null,
"infraorder_id": null,
"parvorder_id": null,
"superfamily_id": null,
"family_id": 135621,
"subfamily_id": 351,
"tribe_id": null,
"subtribe_id": null,
"genus_id": …
```

Add v2 of the API with new ranks

---

app/views/peptidome/analyze.html.erb

This PR adds a new banner to the peptidome analysis page that informs the user about stopping support for the peptidome cluster analysis in the near future.
Screenshot:

Peptidome add warning

---

app/assets/javascripts/mpa/components/App.vue
app/assets/javascripts/spa/components/SingleResults.vue
config/deploy/feat.rb

This PR updates the API URL that's being used under-the-hood to `https://api.unipept.ugent.be`, preparing our application for the changes we are currently making to our server infrastructure.
We've also updated the amount of API requests that are performed in parallel to 2 (instead of 5) in order to decrease the load spikes on our servers.

Update API URL and decrease parallel API requests

---

app/models/sequence.rb
app/models/uniprot_entry.rb
config/environments/production.rb

A lot of the SQL-queries that are produced when the missed cleavage handling feature is enabled are very large (meaning they take a lot of time to execute). This PR splits them up into smaller queries that individually can be executed faster (total time to compute the missed cleavages will probably not have been improved), which fixes an issue where our DBMS was sometimes unresponsive for several minutes.

Split up missed cleavage handling queries

---

src/components/pages/apidocs/Pept2ProtPage.vue

Update the API documentation according to the changes made in https://github.com/unipept/unipept-api/pull/14.

Remove references to EMBL / RefSeq from documentation

---

src/App.vue
src/components/pages/HomePage.vue

This PR changes the URLs for the repositories that need to be used for the version numbers of the different Unipept tools (CLI, API, Web, Desktop, ...). This change is required since we moved the contents of the `unipept-web` repository into the `unipept` repository.

Update repo pointers for version numbers

---

.github/workflows/deploy_action.yml

This PR adds a new GitHub action that can be used to automatically deploy the latest version of the Unipept Web application after a new release has been published for this repository.

Add GitHub action that automatically deploys new versions of web app

---

package-lock.json
package.json

This PR bumps the Unipept Web Components dependency from v2.0.5 to v2.0.6. A list of all changes can be found [here](https://github.com/unipept/unipept-web-components/releases/tag/v2.0.6).

Bump unipept-web-components dependency to v2.0.6

---

src/components/pages/apidocs/OverviewPage.vue
src/components/pages/apidocs/ProtInfoPage.vue
src/components/pages/apidocs/index.ts
src/components/pages/clidocs/OverviewPage.vue
src/components/pages/clidocs/ProtInfoPage.vue
src/components/pages/clidocs/index.ts
src/components/pages/features/APIPage.vue
src/components/pages/features/CLIPage.vue
src/logic/communicators/unipept/UnipeptCommunicator.ts
src/plugins/router.ts

This pull request adds the documentation for the new endpoint in https://github.com/unipept/unipept-api/pull/20.
This PR depends on the previously mentioned pull request. This also means that the examples on the website will fail.

Add documentation pages for the new protinfo page

---

src/components/alerts/MissedCleavageAlert.vue
src/components/cards/analysis/multi/AnalysisSummaryCard.vue
src/components/cards/analysis/multi/CustomTooltip.vue
src/components/cards/analysis/multi/SelectDatasetCard.vue
src/components/cards/analysis/multi/SwitchDatasetCard.vue

This PR introduces a new alert that is always shown above the "advanced missed cleavage handling" option. This option is now always enabled and cannot be unchecked anymore (because of the changes made to the index underlying unipept).
The alert is very prominent, but this is by-design. Users do need to know that this change happened. We will eventually remove this option from Unipept entirely, and that's when the alert will be removed as well. A link to a page on the wiki here is provided to explain this change-in-behavior more in-depth.
Screenshot:

Add information about disabling of the missed cleavage option

---

src/components/pages/AboutPage.vue
src/components/pages/PublicationsPage.vue
src/router/index.ts

I've done some housekeeping and updated the about page, as well as the page with all publications for the Unipept website. The footer of the web app has also been updated to point to our most recent article (on BioRXiv for now) instead of "Unipept 4.0".

Update all publications and the about page

---

src/components/sample/AddSampleCard.vue
src/components/sample/ManageSampleGroup.vue

Fixes the following problems when managing a group's samples:
- Cancel button should only be active when at least one change has been made
- Use search settings from previously added sample when creating a new sample

Fix "manage group" dialog

---

src/components/results/taxonomic/heatmap/DataSourceSelectTable.vue

Fixes issue #1582 
- When using the select box in the header. All currently visible rows should be highlighted and selected

Fix selection in heatmap

---

src/components/analysis/multi/AnalysisSummary.vue
src/components/analysis/multi/AnalysisSummaryTable.vue
src/components/project/Project.vue
src/composables/communication/unipept/useMetaData.ts
src/store/new/SingleAnalysisStore.ts

Do some reworking of the analysis overview page
- Create a textual, readonly, non-clickable component for the search settings.
- List the UniProt version and show the "last analysed on" timestamp.
- Provide a quick link edit option. This can link to the same edit group dialog.
- Add margins to the annotations in the peptide table.

Rework analysis overview page

---

src/components/database/CreateCustomDatabase.vue

Edit the second step of the database creation process:
- Use three columns for the different steps
- Replace the button texts: "By taxa", "By reference proteomes" and "By proteins"
- The description for each option is very similar. Highlight the differences by using a bold font-type.

Changes to step 2 of the database creation process

---

src/components/browsers/DatabaseSummary.vue
src/components/browsers/TaxaBrowser.vue
src/logic/communicators/unipept/taxonomic/TaxonomyResponse.ts
src/logic/communicators/unipept/taxonomic/TaxonomyResponseCommunicator.ts

This PR:
- fixes #1614: disable descendants when an ancestor is already selected. Visualize this in the database summary, when a descendant is selected before its ancestor.
- Compute the total amount of taxa in the database

Disable descendants from taxa that are already selected in TaxaBrowser

---

src/components/browsers/ProteinBrowser.vue
src/components/browsers/ReferenceProteomeBrowser.vue
src/components/browsers/TaxaBrowser.vue
src/components/browsers/useBrowserLoader.ts

This PR provides a fix for issue #1632. I've wrapped the part of the `ProteinBrowser` that performs the updates with the `performIfLast` composable.

Fix protein browser sometimes overrides search results

---

src/components/browsers/ProteinBrowser.vue
src/logic/communicators/unipept/protein/ProteinResponseCommunicator.ts

This PR provides a fix for #1631. The default sort key has been changed from "id" to "uniprot_accession_number".

Fix the sorting by UniProt ID in protein browser

---

src/components/analysis/multi/AnalysisSummary.vue

This PR updates the default filename of exports generated by Unipept such that it also includes the Unipept version number, and the UniProtKB version. Fixes #1609.

Add version info to export filename

---

src/components/pages/documentation/apidocs/APIPept2EcPage.vue
src/components/pages/documentation/apidocs/APIPept2FunctPage.vue
src/components/pages/documentation/apidocs/APIPept2GoPage.vue
src/components/pages/documentation/apidocs/APIPept2InterproPage.vue
src/components/pages/documentation/apidocs/APIPept2LcaPage.vue
src/components/pages/documentation/apidocs/APIPept2ProtPage.vue
src/components/pages/documentation/apidocs/APIPept2TaxaPage.vue
src/components/pages/documentation/apidocs/APIPeptInfoPage.vue
src/components/pages/documentation/apidocs/APIProtInfoPage.vue

By default equateIL is enabled. This was wrongfully reported in the API documentation. This PR fixes this issue

Update documentation (equateIL is enabled by default)

---

src/components/sample/SampleTable.vue

This fixes issue #1646 where updating a duplicated sample also changed the original sample

Deep clone samples instead of shallow copies

---

src/components/browsers/ProteinBrowser.vue

Since the `ProteinBrowser` component is intended to find individual proteins by accession ID or name, it makes no sense that there's a "Last page button". As there are 250 million proteins in UniProtKB at this time, it's simply infeasible to provide this kind of functionality at this point.
Provides a fix for https://github.com/unipept/unipept-api/issues/73

Hide last page button for `ProteinBrowser`
