unipept/unipept

app/controllers/sequences_controller.rb
app/models/peptide.rb
app/models/uniprot_entry.rb
app/views/sequences/show.html.erb

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/89) by @bmesuere on Thu Aug 30 2012 at 12:39._
_Merged by @bmesuere on Fri Sep 28 2012 at 16:08._

add support for missed cleavages

---

app/models/sequence.rb
config/deploy.rb
tools/scripts/batchSearch.sh
tools/scripts/griet.sh
tools/scripts/grietDataRunner.txt

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/166) by @bmesuere on Sat Oct 19 2013 at 13:46._
_Merged by @bmesuere on Sat Oct 19 2013 at 14:17._

Expand the batch process options

---

Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/multi_search.js
app/assets/javascripts/pancore.js
app/assets/javascripts/sequence_show.js
app/assets/stylesheets/application.css.less
app/controllers/download_controller.rb
app/controllers/imagemagick_controller.rb
app/controllers/sequences_controller.rb
app/views/sequences/multi_search.html.erb
app/views/shared/_save_image_modal.html.erb

#164 #174 #153 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/183) by @bmesuere on Fri Nov 01 2013 at 19:08._
_Merged by @bmesuere on Thu Nov 21 2013 at 18:20._

impove exports

---

app/assets/javascripts/application.js
app/assets/javascripts/multi_search.js
app/assets/javascripts/sequence_show.js
app/views/layouts/application.html.erb
app/views/pages/admin.html.erb

#178
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/193) by @bmesuere on Sat Nov 16 2013 at 14:52._
_Merged by @bmesuere on Sat Nov 16 2013 at 15:21._

remove qbaka

---

config/deploy.rb

This should close #198.
This is a quick test and needs to be tested before merge.
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/270) by ghost on Sat May 03 2014 at 18:10._
_Merged by @bmesuere on Mon May 05 2014 at 10:31._

migrate to capistrano 3

---

app/assets/javascripts/peptidome/pancore.js
app/assets/javascripts/peptidome/phylogram.js
app/assets/javascripts/peptidome/simMatrix.js
app/assets/javascripts/workers/pancore_worker.js
vendor/assets/javascripts/newick/newick.js

Closes #242 #308 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/319) by @bmesuere on Tue May 13 2014 at 22:31._
_Merged by @bmesuere on Thu May 15 2014 at 10:51._

swap branches feature

---

app/assets/javascripts/application.js
app/assets/javascripts/datasets.js
app/assets/javascripts/multi_search.js
app/assets/javascripts/peptidome/pancore.js
app/assets/javascripts/sequence_show.js
app/controllers/api/api_controller.rb
app/controllers/application_controller.rb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
backend/database/data.sql
config/environments/development.rb
config/environments/production.rb
config/initializers/stathat.rb

Needed for #354 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/359) by @bmesuere on Mon Jun 02 2014 at 16:05._
_Merged by @bmesuere on Mon Jun 02 2014 at 21:20._

Make some features optional

---

app/assets/javascripts/application.js
app/assets/javascripts/multi_search.js
app/assets/stylesheets/application.css.less
app/views/sequences/multi_search.html.erb

fixes #195 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/360) by @bmesuere on Tue Jun 03 2014 at 15:58._
_Merged by @bmesuere on Tue Jun 03 2014 at 16:44._

Enable optional fixed colors for sunburst

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/multi_search.js
app/assets/stylesheets/application.css.less
app/views/sequences/multi_search.html.erb

Closes #152 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/386) by @bmesuere on Sun Jul 06 2014 at 17:26._
_Merged by @bmesuere on Sun Jul 06 2014 at 17:28._

Add copy to clipboard functionality

---

app/assets/javascripts/peptidome/myGenomes.js
app/assets/javascripts/peptidome/pancore.js
app/assets/javascripts/workers/mygenome_worker.js
app/assets/javascripts/workers/pancore_worker.js
app/assets/stylesheets/application.css.less
app/views/layouts/_footer.html.erb
app/views/peptidome/analyze.html.erb
config/application.rb

Reimplement the myGenomes feature using indexedDB.
Closes #285 #286 #287 #288 #315
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/390) by @bmesuere on Thu Jul 10 2014 at 10:46._
_Merged by @bmesuere on Tue Jul 15 2014 at 19:23._

myGenomes 2.0

---

app/assets/javascripts/sequence_show.js
app/assets/stylesheets/sequence_show.css.less
app/controllers/sequences_controller.rb
app/views/sequences/show.html.erb

Closes #91 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/393) by @bmesuere on Thu Aug 07 2014 at 17:00._
_Merged by @bmesuere on Fri Aug 08 2014 at 14:41._

Use the new treeview for tryptic peptide analysis

---

backend/java/src/main/java/org/unipept/tools/commandline/LCACalculator.java
backend/scripts/dumpDatabase.sh
backend/scripts/loadDatabase.sh

The sequel of https://github.ugent.be/bmesuere/unipept/pull/384
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/398) by @bmesuere on Sat Aug 16 2014 at 10:44._
_Merged by @bmesuere on Sun Aug 17 2014 at 14:04._

rewrite the LCA calculator in java, part 2

---

app/controllers/api/api_controller.rb
app/controllers/api/apidocs_controller.rb
app/views/api/api/pept2lca.json.erb
app/views/api/api/pept2prot.json.erb
app/views/api/api/pept2taxa.json.erb
app/views/api/apidocs/pept2lca.html.erb
app/views/api/apidocs/pept2prot.html.erb
app/views/api/apidocs/pept2taxa.html.erb

Closes #406, closes #408.
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/409) by @bmesuere on Wed Aug 27 2014 at 12:12._
_Merged by @bmesuere on Wed Aug 27 2014 at 14:08._

API improvements

---

app/assets/javascripts/multi_search.js
app/assets/stylesheets/metaproteomics_results.css.less
app/views/sequences/multi_search.html.erb

Closes #421 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/423) by @bmesuere on Sat Oct 04 2014 at 15:21._
_Merged by @bmesuere on Sat Oct 04 2014 at 15:22._

Add reset buttons to sunburst, treemap and treeview

---

.gitignore
Gemfile
Gemfile.lock
config/initializers/stathat.rb
test/controllers/api/api_controller_test.rb
test/controllers/pages_controller_test.rb
test/controllers/peptidome_controller_test.rb
test/controllers/sequences_controller_test.rb
test/fixtures/lineages.yml
test/fixtures/peptides.yml
test/fixtures/sequences.yml
test/fixtures/taxons.yml
test/fixtures/uniprot_entries.yml
test/fixtures/users.yml
test/models/node_test.rb

Starting with 98.61%: https://coveralls.io/jobs/3585072
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/442) by @bmesuere on Sat Dec 06 2014 at 14:14._
_Merged by @bmesuere on Sat Dec 06 2014 at 16:17._

achieve 100% test coverage

---

app/controllers/api/api_controller.rb
app/models/refseq_cross_reference.rb
app/models/uniprot_entry.rb
app/views/api/api/pept2prot.json.erb
app/views/api/apidocs/pept2prot.html.erb
config/deploy/feat.rb
test/controllers/api/api_controller_test.rb
test/fixtures/refseq_cross_references.yml
test/models/refseq_cross_reference_test.rb

Closes #449 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/452) by @bmesuere on Fri Jan 16 2015 at 14:42._
_Merged by @bmesuere on Tue Jan 27 2015 at 10:40._

add embl and refseq cross references to the pept2prot api

---

backend/src/main/java/org/unipept/xml/UniprotEntry.java
backend/src/main/java/org/unipept/xml/UniprotHandler.java

Fix #503
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/506) by @ninewise on Thu Jun 18 2015 at 14:07._
_Merged by @ninewise on Thu Jun 18 2015 at 14:37._

add the submitted name if recommended name is absent

---

app/assets/javascripts/workers/pancore_worker.js
app/views/peptidome/analyze.html.erb

Closes #513 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/516) by @bmesuere on Sat Jul 04 2015 at 16:02._
_Merged by @bmesuere on Mon Jul 06 2015 at 17:34._

Add ochiai similarity, remove weighted average

---

backend/database/structure.sql
backend/database/structure_no_index.sql

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/573) by @ninewise on Thu May 19 2016 at 14:14._
_Merged by @ninewise on Thu May 19 2016 at 14:15._

remove position column from database tables

---

backend/createEcNumbers.sh.in
backend/makefile.in
backend/proteomes.sh.in
backend/type_strains.sh.in

As advised by `@svsegher` .
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/582) by @ninewise on Tue Jun 14 2016 at 17:09._
_Merged by @bmesuere on Tue Jun 14 2016 at 21:13._

add pipefail to the shell options

---

backend/database/index.sh

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/585) by @ninewise on Mon Jun 20 2016 at 21:13._
_Merged by @ninewise on Mon Jun 20 2016 at 21:14._

fix rename in the indexing script

---

package.json

Needed for the merged changes of #631 
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/637) by @beardhatcode on Tue May 29 2018 at 10:24._
_Merged by @bmesuere on Tue May 29 2018 at 10:49._

Set minimum yarn version to 1.0.0

---

README.md
app/views/api/apidocs/index.html.erb
app/views/layouts/_footer.html.erb
app/views/pages/about.html.erb
app/views/pages/publications.html.erb
app/views/shared/_save_image_modal.html.erb

This is the exact changes proposed on github.com
fixes #627
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/638) by @beardhatcode on Fri Jun 08 2018 at 11:04._
_Merged by @bmesuere on Mon Jun 11 2018 at 12:08._

New DOI links

---

backend/database/structure.sql
backend/database/structure_no_index.sql

fixes #636 
I checked the logs and updated the sizes to be able to include all text
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/645) by @beardhatcode on Wed Aug 08 2018 at 17:27._
_Merged by @bmesuere on Mon Aug 13 2018 at 15:30._

fix(proteomes db): increase col size

---

app/assets/javascripts/mpa/searchtree.js
app/assets/stylesheets/metaproteomics_results.css.less

fixes #621
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/646) by @beardhatcode on Wed Aug 08 2018 at 17:39._
_Merged by @bmesuere on Mon Aug 13 2018 at 15:27._

fix(mpa style): Add ellipsis to sequences longer than treeviewcontainer

---

app/views/api/clidocs/casestudy_metagenomics.html.erb

@bmesuere would you happen to know the RAM type in Adler?
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/649) by @ninewise on Wed Aug 22 2018 at 11:44._
_Merged by @bmesuere on Tue Jan 15 2019 at 14:04._

add complete command as recap

---

app/assets/javascripts/mpa/dataset.js
app/assets/javascripts/mpa/index.js
app/assets/javascripts/mpa/resultset.js
app/assets/javascripts/mpa/worker.js
app/views/sequences/show.html.erb

Fix problems form  #653
_[Original pull request](https://github.ugent.be/unipept/unipept/pull/657) by @beardhatcode on Fri Sep 21 2018 at 15:07._
_Merged by @bmesuere on Tue Jan 15 2019 at 14:05._

Fix small manuscript issues 

---

backend/makefile.in

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/666) by @ninewise on Thu Mar 14 2019 at 09:23._
_Merged by @ninewise on Thu Mar 28 2019 at 10:46._

NCBI added 3 subcohorts

---

backend/configure
backend/makefile.in

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/667) by rbmaerte on Wed Mar 27 2019 at 11:20._
_Merged by @ninewise on Thu Mar 28 2019 at 10:40._

build-index is umgap build-index

---

app/views/layouts/_footer.html.erb

_[Original pull request](https://github.ugent.be/unipept/unipept/pull/670) by rbmaerte on Fri May 17 2019 at 09:42._
_Merged by @bmesuere on Sat May 18 2019 at 17:35._

Fix typo in DOI link

---

backend/make-on-hpc.sh
backend/makefile.in

This should speed up FA-calculation a little. Could you verify this is equivalent to yours, @pcvthien?

split the FA recipes to reuse sorted tables

---

app/controllers/datasets_controller.rb
app/controllers/handle_options_controller.rb
app/controllers/mpa_controller.rb
app/controllers/private_api_controller.rb
config/routes.rb

This pull request configures all API-endpoints that are used by the Unipept Desktop application to support Cross-Origin-Resource-Sharing (which is required by the desktop application).

add support for CORS

---

app/assets/stylesheets/layout.css.less
app/views/layouts/application.html.erb
yarn.lock

The page's footer sometimes covers up some content. This PR fully pushes the footer to the bottom of the page, fixing this issue.

fully push footer to bottom

---

app/assets/javascripts/mpa/components/pages/AnalysisPage.vue
config/application.rb
package.json
yarn.lock

This PR updates the Unipept Web Components version being used to the newest one (with some additional bug fixes).

Update to newest version of UWC

---

package.json
yarn.lock

I had to make a minor change to the UWC package.json to make sure deployment of the project succeeds. This means that I also had to update the UWC-version in this repository.

Fix deploy due to change in web components

---

Gemfile
Gemfile.lock
app/assets/javascripts/mpa/components/App.vue
config/application.rb
config/deploy/dev.rb
config/environments/production.rb
config/webpack/environment.js
config/webpack/optimization.js
config/webpack/resolves.js
config/webpacker.yml
package.json
yarn.lock

Bumps Unipept Web Components to version 0.1.8 which includes some additional fixes.

update/web components 0.1.8

---

app/controllers/mpa_controller.rb

Fix equate_il must be boolean error

---

app/assets/javascripts/spa/components/search/SearchPeptideCard.vue

Fixes SequenceTooShort error

---

app/controllers/private_api_controller.rb

Fixes the error described in #1026

Retrieve lineages in all branches to fix nil-error

---

package.json

Fixes the treeview SVG downloads

Bump UWC version

---

app/views/api/desktop/index.html.erb

This PR fixes the download link in the documentation for all platforms.

Fix download link on all platforms

---

.github/workflows/ruby.yml

This PR updates the way we install and use Ruby and JS in our github actions. The workflow is simplified and execution is faster.

Update github actions workflows

---

src/components/cards/analysis/multi/LoadDatasetsCard.vue
src/components/cards/analysis/single/TrypticPeptideAnalysisSearchCard.vue

This PR updates the textual inconsistencies in the application that were reported by users in #1561.

Update some of the textual inconsistencies that were reported by users

---

src/components/project/Project.vue

Select the first sample when needed

---

src/components/tables/LineageTable.vue
src/logic/Constants.ts
src/logic/ontology/taxonomic/Ncbi.ts

This PR improves the Unipept web application with support for the new Domain and Realm ranks in the NCBI taxonomy.

Make Unipept compatible with new NCBI ranks

---

src/components/filesystem/FileUpload.vue

Fix upload button stays disabled after drag-and-dropping

---

src/components/sample/AddSampleStepper.vue

Fix scroll in file upload card that is too tall

---

src/components/filesystem/Filesystem.vue
src/components/filesystem/FilesystemGroup.vue
src/components/project/ProjectView.vue

Redo the styling of the file explorer

---

src/components/filesystem/FileUpload.vue

This PR provides a fix for issue #1641.

Fix drag and drop for multiple files

---

src/components/browsers/DatabaseSummary.vue
src/components/browsers/useDatabaseSummary.ts
src/logic/communicators/unipept/protein/ProteinResponseCommunicator.ts

This PR fixes:
- Incorrect batch size when processing proteins
- Fixes the amount of pills to render. This partially fixes blocking the main thread
- Fixes the ontology retrieval by using a set. This also partially fixes blocking the main thread

Fix batches, fix amount of pills to render, fix ontology retrieval
